[package]
name = "rocket"
version = "0.2.0"
authors = ["Adolfo Ochagav√≠a <aochagavia92@gmail.com>"]
build = "build.rs"

[dependencies]
itertools-num = "0.1.1"
piston_window = "0.64.0"
piston2d-opengl_graphics = "0.42.1"
rand = "0.3.14"
