[package]
name = "rocket"
version = "0.2.0"
authors = ["Adolfo Ochagav√≠a <aochagavia92@gmail.com>"]
build = "build.rs"

[dependencies]
itertools = "0.4.19"
piston = "0.26.0"
piston_window = "0.54.0"
piston2d-graphics = "0.17.3"
piston2d-opengl_graphics = "0.34.0"
rand = "0.3.14"

[profile.release]
debug = true
