[package]
name = "rocket"
version = "1.0.0"
authors = ["Adolfo Ochagav√≠a <aochagavia92@gmail.com>"]
build = "build.rs"

[dependencies]
clippy = { version = "0.0.118", optional = true }
itertools-num = "0.1.1"
rand = "0.3.14"
# This is commented out until ggez releases a new version. For the time being
# we're just depending on a specific rev of the repository for the new features.
# ggez = "0.4"

[dependencies.ggez]
git = "https://github.com/ggez/ggez.git"
rev = "b208c6c8b22e48ea2a7b4d7fe02bd88454330640"

[features]
default = []
