[package]
name = "rocket"
version = "1.0.0"
authors = ["Adolfo OchagavÃ­a <aochagavia92@gmail.com>"]

[dependencies]
clippy = { version = "0.0.118", optional = true }
itertools-num = "0.1.1"
rand = "0.4.2"

[features]
default = []
debug = []